Repository dnsimple/dnsimple-node, pull requests merged in 2019-07, with the labels that each got.

#19 Updates security vulnerabilities
  package-lock.json
  package.json
Labels: task

#21 Release 3.0.0
  .travis.yml
  CHANGELOG.md
  README.md
  lib/dnsimple.js
  package-lock.json
  package.json
Labels: dependencies, enhancement

#22 Drop the dependency on `npm` package
  package-lock.json
  package.json
Labels: enhancement

#23 Release 3.0.1
  CHANGELOG.md
  lib/dnsimple.js
  package.json
Labels: enhancement, ready-for-review
