Repository dnsimple/dnsimple-node, pull requests merged in 2021-04, with the labels that each got.

#89 Drop the inexistent domains.resetDomainToken method
  CHANGELOG.md
  lib/dnsimple/domains.js
  test/dnsimple/domains.spec.js
  test/fixtures.http/resetDomainToken/success.http
Labels: bug, ready-for-review, requires-major-release

#88 Implement registrar methods for Domain Prices API
  CHANGELOG.md
  lib/dnsimple/registrar.js
  test/dnsimple/registrar.spec.js
  test/fixtures.http/getDomainPrices/failure.http
  test/fixtures.http/getDomainPrices/success.http
Labels: enhancement, ready-for-review

#92 Adds NodeJS v16 to Travis
  .travis.yml
  CHANGELOG.md
  LICENSE.txt
  package-lock.json
  package.json
Labels: ready-for-review
